# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Idle daemon (screensaver, display off, lock, suspend)
# exec-once = uwsm-app -- bash ~/.config/omarchy/hooks/swayidle

# Generate dynamic workspace layout based on monitor count
exec-once = ~/waybar-workspaces
